AWSTemplateFormatVersion: "2010-09-09"
Description: CI/CD Pipeline for Elastic Beanstalk Application
Parameters:
  RepositoryArn:
    Type: String
    Description: Arn of your CodeCommit repo.
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Can contain only ASCII characters.

  RepositoryBranch:
    Type: String
    Description: Name of the branch in the CodeCommit repo
    Default: master
    AllowedPattern: "[\\x20-\\x7E]*"
    ConstraintDescription: Can contain only ASCII characters.

  EBApplicationName:
    Type: String
    Description: Name of Elastic Beanstalk Application

  EBEnvironmentName:
    Type: String
    Description: Environment Name of Elastic Beanstalk Application


Resources:
  ArtifactStore:
    Type: AWS::S3::Bucket

  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CodeCommitAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - codecommit:Get*
                  - codecommit:List*
                  - codecommit:UploadArchive
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:CancelUploadArchive
                  - codecommit:BatchGetRepositories
                  - codecommit:GitPull
                Effect: Allow
                Resource:
                  - !Ref RepositoryArn
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:PutObject
                Effect: Allow
                Resource:
                  - !GetAtt ArtifactStore.Arn
                  - !Sub "arn:${AWS::Partition}:s3:::codepipeline*"
                  - !Sub "arn:${AWS::Partition}:s3:::elasticbeanstalk*"
                  - Fn::Sub:
                    - "${Store}/*"
                    - Store: !GetAtt ArtifactStore.Arn
        - PolicyName: CodeDeployAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - codedeploy:CreateDeployment
                  - codedeploy:GetApplicationRevision
                  - codedeploy:GetDeployment
                  - codedeploy:GetDeploymentConfig
                  - codedeploy:RegisterApplicationRevision
                Effect: Allow
                Resource: "*"
        - PolicyName: EBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - elasticbeanstalk:*
                  - ec2:*
                  - elasticloadbalancing:*
                  - autoscaling:*
                  - cloudwatch:*
                  - s3:*
                  - sns:*
                  - cloudformation:*
                  - rds:*
                  - sqs:*
                  - ecs:*
                  - iam:PassRole
                Effect: Allow
                Resource: "*"


#        - PolicyName: LambdaAccess
#          PolicyDocument:
#            Version: "2012-10-17"
#            Statement:
#              - Action:
#                  - lambda:InvokeFunction
#                  - lambda:ListFunctions
#                Effect: Allow
#                Resource: "*"
#       - PolicyName: CodeDeployAccess
#          PolicyDocument:
#            Version: "2012-10-17"
#            Statement:
#              - Action:
#                  - elasticbeanstalk:*
#                  - ec2:*
#                  - elasticloadbalancing:*
#                  - autoscaling:*
#                  - cloudwatch:*
#                  - s3:*
#                  - sns:*
#                  - cloudformation:*
#                  - rds:*
#                  - sqs:*
#                  - ecs:*
#                  - iam:PassRole
#                Effect: Allow
#                Resource: "*"

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactStore
      Stages:
        - Name: Source
          Actions:
          - Name: Source
            ActionTypeId:
              Category: Source
              Owner: AWS
              Version: '1'
              Provider: CodeCommit
            OutputArtifacts:
              - Name: AppSourceArtifact
            Configuration:
              BranchName:
                Ref: RepositoryBranch
              RepositoryName: !Select
                  - 5
                  - !Split
                    - ":"
                    - !Ref RepositoryArn
            RunOrder: 1
        - Name: Production
          Actions:
          - Name: Beanstalk
            ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: '1'
              Provider: ElasticBeanstalk
            InputArtifacts:
              - Name: AppSourceArtifact
            Configuration:
              ApplicationName: !Ref EBApplicationName
              EnvironmentName: !Ref EBEnvironmentName
            RunOrder: 1

Outputs:
  CodePipelineURL:
    Description: Pipeline URL
    Value:
      Fn::Join:
      - ''
      - - https://console.aws.amazon.com/codepipeline/home?region=
        - Ref: AWS::Region
        - "#/view/"
        - Ref: CodePipeline
